### ISSUE TITLE
[Usecase] [Help] How to start textcomposition ?

### ISSUE THREAD

**Issue by sagarkardani** [ryancheung/ImeSharp#13]
Thanks for this great wrapper.

I am totally new to [IME](https://docs.microsoft.com/en-us/windows/win32/intl/input-method-manager-reference) and all [TSF](https://docs.microsoft.com/en-us/windows/win32/tsf/text-services-framework) related APIs. I was able to start the Demo Project successfully. On textinput InputMethod.TextInputCallback is fired. Now I want to start my custom text composition based on my input and want to show candidates in window like below.
![image](https://user-images.githubusercontent.com/60609139/139522473-aab5d11a-e008-4e8e-b6ff-28536d8907f2.png)

Can you tell me how to start text composition and show window ?

Regards,
Sagar

**Comment by ryancheung** [comment]
You probrably need this https://github.com/ryancheung/ImeSharp/blob/master/ImeSharp/InputMethod.cs#L77

**Comment by ryancheung** [comment]
You probrably need set `showOSImeWindow` to true on `InputMethod.Initialize()`  method call here:
https://github.com/ryancheung/ImeSharp/blob/00e40e4e3348ee9204c93b4e4f1b2a3cce33275a/ImeSharp.Demo/Form1.cs#L66

**Comment by sagarkardani** [comment]
@ryancheung
Thanks for reply.

That I did already. But where to start my custom text composition and how to trigger InputMethod.TextCompositionCallback ? Can you give me any reference link ?
