### ISSUE TITLE
How should I paste the word to third-party program?

### ISSUE THREAD

**Issue by 102425074** [ryancheung/ImeSharp#9]
I am trying to code an input method by this.

I tried the demo program and it runs well.

However, the demo program only works in itself.

Now I am about to paste the word to third-party programs (such as windows notepad).

How can I achieve this? Thank you.

**Comment by ryancheung** [comment]
You may need this https://github.com/CopyText/TextCopy

**Comment by 102425074** [comment]
> You may need this https://github.com/CopyText/TextCopy

I am afraid there is a misconstrue. I don't want to copy it to the clipboard and paste it somewhere.

I just want it to be the same as the normal input method. When I typing with it, the word will appear on the notepad.

But now it seems the word only can appear on itself while can't appear on the third-party program.

**Comment by ryancheung** [comment]
It's not what this library does I think. There's no way to use this libary make word appear in another program, unless you write the progrem yourself and integrate with this library to enable IME support.

**Comment by 102425074** [comment]
> It's not what this library does I think. There's no way to use this libary make word appear in another program, unless you write the progrem yourself and integrate with this library to enable IME support.

All right, thank you so much.
